apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: myapp
type: Opaque
stringData:
  DATABASE_URL: "${database_url}"
  JWT_SECRET: "${jwt_secret}"
  JWT_EXPIRE_MINUTES: "${jwt_expire_minutes}"
