apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: 135.171.22.205.nip.io
      http:
        paths:
          # API: /api/... -> /... (strip /api)
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80

          - path: /(openapi\.json)
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80

          # MinIO public file: /minio-public/... -> /... (strip /minio-public)
          - path: /minio-public/(.*)
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9000

          # Frontend: /... -> /... (giữ nguyên path)
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80

    - host: minio.135.171.22.205.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9001
